version: "3.8"

services:
  fragments:
    build: .
    init: true
    ports:
      - "8080:8080"
    environment:
      - API_URL=http://localhost:8080
      - HTPASSWD_FILE=tests/.htpasswd
      - LOG_LEVEL=debug
      - AUTH_STRATEGY=basic
      - FRAGMENTS_BACKEND=memory
      - AWS_REGION=us-east-1
      - AWS_S3_BUCKET_NAME=fragments
      - AWS_S3_ENDPOINT_URL=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_SESSION_TOKEN=test
    depends_on:
      - dynamodb-local
      - localstack

  dynamodb-local:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb
      - DEBUG=1
